'use client';
import { Inter, Roboto_Mono , Plus_Jakarta_Sans} from "next/font/google";
import "./globals.css";
import dynamic from 'next/dynamic';

const plusJakartaSans = Plus_Jakarta_Sans({ subsets: ["vietnamese"] });
const inter = Inter({ subsets: ["vietnamese"] });
// const robotoMono = Roboto_Mono({ subsets: ["vietnamese"] });

const ConvexClientProvider = dynamic(
  () => import('./ConvexClientProvider'),
  { ssr: false }
);

const Provider = dynamic(
  () => import('./provider'),
  { ssr: false }
);

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${plusJakartaSans.className} ${inter.className}`}>
        <ConvexClientProvider>
          <Provider>
            {children}
          </Provider>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
